# default nginx conf meant for copying into nginx container on build
server {
         listen 80;
         listen [::]:80;

         server_name localhost;
         root /usr/share/nginx/html;
         index index.html;

         resolver 10.88.0.1 127.0.0.53 valid=30s;
         resolver_timeout 5s;

         location /api/ {
                set $backend "abeonasec-api";
                proxy_pass http://$backend:8000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
         }

         location / {
                try_files $uri $uri/ /index.html;
         }
        # Optional: configure logging
        error_log /var/log/nginx/vue-app-error.log;
        access_log /var/log/nginx/vue-app-access.log;
  }