# default nginx conf meant for copying into nginx container on build
server {
  listen 80;
  listen [::]:80

  root /usr/share/nginx/html/abeonasec-spa;
  index index.html

  location / {
    try_files $uri $uri/ /index.html;
  }
}
